<script>
  import { navlink } from 'svelte-navlink-action'
  import Footer from '~/layout/Footer.svelte'
  import Nav from '~/layout/Nav.svelte'
  import '~/styles/app.scss'

  // DEFINES IF THE PAGE IS WIDTH-CONSTRAINED
  let constrained = true
  let year = new Date().getFullYear()
</script>

<svelte:head>
  <link rel="icon" type="image/svg" href="/favicon.png">
  <link rel="preconnect" href="https://api.itty.cards" crossorigin>
  <title>SvelteKit Template</title>
  <meta name="description" content="This site was generated by Kevin's SvelteKit Template" />
  <meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
  <html lang="en" />
</svelte:head>

<main>
  <Nav version sticky collapsible horizontal>
    <span slot="brand">
      it<strike>t</strike>y.sh
    </span>

    <a href="/basics" use:navlink>Basics</a>
    <a href="/forms" use:navlink>Forms Elements</a>
    <a href="/misc" use:navlink>Misc</a>
    <a href="/" use:navlink>Home (default)</a>
    <a href="/" use:navlink={{ exact: true }}>Home (exact)</a>
    <a href="https://aimandkevinbutaimeesnamefirst.com">Another Site</a>
    <a href="https://itty.cards.com">itty.cards</a>
    <a href="https://itty.sh">itty.sh</a>
    <a href="https://aimandkevinbutaimeesnamefirst.com">And Yet Another</a>
    <a href="https://itty.cards.com">itty.cards</a>
  </Nav>

  <section class:constrained>
    <slot />
  </section>

  <Footer constrained={constrained}>
    &copy; {year} Some Company. All rights reserved.
  </Footer>
</main>

<style lang="scss">
  main {
    display: flex;
    flex-flow: column;
    height: 100%;
    overflow: scroll;

    section {
      flex: 1;
      display: flex;
      flex-flow: row wrap;
      justify-content: center;
    }
  }

  small {
    font-size: 0.5em;
    letter-spacing: 0em;
    color: var(--foreground-25);
    top: -0.4rem;
    position: relative;
  }
</style>
